name: Build

on:
  push:
    branches:
      - develop
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: install libraries
      run: |
        sudo apt update
        sudo apt install libgtk-3-dev build-essential automake autoconf libharfbuzz-dev libjpeg-dev libopenjp2-7-dev libjbig2dec0-dev libpng-dev libfreetype6-dev libarchive-dev libmupdf-dev libjpeg62 libssl-dev libmujs-dev libsqlite3-dev libgumbo-dev
    - name: run autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make -j $(nproc)
    - name: get AppImageTool
      run: |
        wget -c https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage
        chmod +x ./appimagetool-x86_64.AppImage
    - name: get linuxdeploy/linuxdeploy
      run: |
        wget -c https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        chmod +x ./linxdeploy-x86_64.AppImage
    - name: run AppImageTool
      run: ARCH=x86_64 appimagetool-x86_64.AppImage ./appimage_dir
    - name: run linuxdeploy
      run: linuxdeploy-x86_64.AppImage -e ./src/simple_comics_viewer -d ./for_appimage_assets/simple_comics_viewer.desktop -i ./for_appimage_assets/icon.svg --appdir appimage_dir
    - uses: actions/upload-artifact@v3
      with:
        name: Simple_Comics_Viewer-${{ github.ref_name }}x86_64.AppImage
        path: ./Simple_Comics_Viewer-x86_64.AppImage
